version: "3"
services:

  mysql-cmdline:
      image: mysql:latest
      container_name: mysql-cmdline
      external_links:
        - mysql:db
      command: bash -c "echo 'drop user if exists '\''www'\''@'\''%'\'';create user '\''www'\''@'\''%'\'' identified by '\''$$3cureUS'\'';drop database if exists cs4501;create database cs4501 character set utf8;grant all on cs4501.* to '\''www'\''@'\''%'\'';drop database if exists test_cs4501; grant all on test_cs4501.* to '\''www'\''@'\''%'\'';'"


  models:
    image: tp33/django
    container_name: models
    external_links:
      - mysql:db
    networks:
      - backend
      - service_mesh
    ports:
      - "8001:8000"
    volumes:
      - ./isa:/app
    command: "mod_wsgi-express start-server --log-to-terminal --reload-on-changes ./isa/wsgi.py"

  experience:
    image: tp33/django
    container_name: experience
    networks:
      - service_mesh
      - public
    ports:
      - "8002:8000"
    volumes:
      - ./experience:/app
    command: "mod_wsgi-express start-server --log-to-terminal --reload-on-changes ./experience/wsgi.py"

  front:
    image: tp33/django
    container_name: front
    networks:
      - public
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    command: "mod_wsgi-express start-server --reload-on-changes ./front/wsgi.py"

networks:
  backend:
  public:
  service_mesh: