version: "3"
services:

  models:
    image: tp33/django
    container_name: models
    external_links:
      - mysql:db
    networks:
      - backend
      - service_mesh
    ports:
      - "8001:8000"
    volumes:
      - ./isa:/app
    command: "mod_wsgi-express start-server --reload-on-changes ./isa/wsgi.py"

  experience:
    image: tp33/django
    container_name: experience
    networks:
      - service_mesh
      - public
    ports:
      - "8002:8000"
    volumes:
      - ./experience:/app
    command: "mod_wsgi-express start-server --reload-on-changes ./experience/wsgi.py"

  front:
    image: tp33/django
    container_name: front
    networks:
      - public
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
    command: "mod_wsgi-express start-server --reload-on-changes ./front/wsgi.py"

networks:
  backend:
  public:
  service_mesh: