# Generated by Django 2.2.4 on 2020-02-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product'),
        ('main', '0002_review'),
    ]

    operations = [
    ]
