# Generated by Django 2.2.4 on 2020-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('authenticator', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
