# Generated by Django 2.2.4 on 2020-05-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(unique=True)),
                ('recommended_items', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
